version: "3.7"
services:
  timescale:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cookbook
      PGDATA: /var/lib/postgresql/data/pgdata