micronaut:
  application:
    name: cookbook
  metrics:
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
endpoints:
  beans:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  caches:
    enabled: true
    sensitive: false
  stop:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
datasources:
  default:
    url: jdbc:postgresql://192.168.99.100:5432/cookbook
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
my:
  prop: dev-property-value
config:
  properties:
    id: 42
    name: recipe name
    description: recipe description
